torch2424/wasm-by-example

examples/exports/demo/assemblyscript/exports.js
examples/exports/exports.assemblyscript.en-us.md
examples/hello-world/demo/assemblyscript/hello-world.js
examples/hello-world/hello-world.assemblyscript.en-us.md
examples/importing-javascript-functions-into-webassembly/demo/assemblyscript/index.js
examples/importing-javascript-functions-into-webassembly/importing-javascript-functions-into-webassembly.assemblyscript.en-us.md
examples/reading-and-writing-audio/demo/assemblyscript/index.js
examples/reading-and-writing-audio/reading-and-writing-audio.assemblyscript.en-us.md
examples/reading-and-writing-graphics/demo/assemblyscript/index.js
examples/reading-and-writing-graphics/reading-and-writing-graphics.assemblyscript.en-us.md
examples/webassembly-linear-memory/demo/assemblyscript/index.js
examples/webassembly-linear-memory/webassembly-linear-memory.assemblyscript.en-us.md

As the title states! Also fixed wasm serving with: https://github.com/torch2424/devops/commit/c26410d2a40fe4a2538f55730969dddb932f11fb

Fixed AS demo Wasm import URLs

---

examples/reading-and-writing-audio/demo/rust/index.html
examples/reading-and-writing-graphics/demo/assemblyscript/index.html
examples/reading-and-writing-graphics/demo/rust/index.html

closes #16 
Tested chrome safari firefox 😄 
In firefox:

Fixed graphics cross browser

---

README.md

add a start guide to beginners

📖 add a start guide to beginners

---

shell/index.html

Fix one typo on the introduction

Fix typo on introduction

---

examples/exports/demo/rust/src/lib.rs
examples/exports/exports.rust.en-us.md
examples/hello-world/demo/rust/src/lib.rs
examples/hello-world/hello-world.rust.en-us.md
examples/importing-javascript-functions-into-webassembly/demo/rust/src/lib.rs
examples/importing-javascript-functions-into-webassembly/importing-javascript-functions-into-webassembly.rust.en-us.md
examples/reading-and-writing-audio/demo/rust/src/lib.rs
examples/reading-and-writing-audio/reading-and-writing-audio.rust.en-us.md
examples/reading-and-writing-graphics/demo/rust/src/lib.rs
examples/reading-and-writing-graphics/reading-and-writing-graphics.rust.en-us.md
examples/strings/demo/rust/src/lib.rs
examples/strings/strings.rust.en-us.md
examples/webassembly-linear-memory/demo/rust/src/lib.rs
examples/webassembly-linear-memory/webassembly-linear-memory.rust.en-us.md

fix(chore): fix typo in the Rust samples

---

shell/index.html
shell/styles/index.css

- link hover color;
- link underline using border;
- gradient hr;
- add .highlight class;

add some colors

---

shell/partials/header.html

add wasm logo to header

---

shell/styles/index.css

closes #50 
Iterated on the awesome colors introduced by @eduardogoncalves . :+1: Made things a little easier to read :smile:

Did some slight color changes

---

shell/index.html
shell/styles/index.css

Blockquote index

---

shell/styles/index.css

add blockquote styles

---

shell/about.html
shell/styles/index.css

Blockquote about me

---

README.md
shell/about.html
shell/index.html
shell/partials/head.html
shell/styles/index.css

relates to #47 
closes #49 
* This fixes up some of the blockquote colors for a11y. 
* Added Google Analytics, included privacy statements.
* Did some general text updating, and content shifting :smile: 
cc @eduardogoncalves just FYI :smile: :+1:

Followup blockquote fixes, Added Google Analytics, General Housekeeping

---

examples/introduction/introduction.all.en-us.md

Fix trivial typo.
I'll probably do more spell check as I go through the sections. Thanks for the cool guide!

Fix small typo in introduction section

---

README.md
examples/hello-world/hello-world.c.en-us.md

I hope this is helpful, let me know what you think!

Add C example using Emscripten

---

examples/hello-world/hello-world.c.en-us.md

Simple fix for linting after I commited directly to master 😂

Fixed linting for C examples

---

examples/reading-and-writing-audio/reading-and-writing-audio.rust.en-us.md

change **reccomended** to **recommended**

fix typo on reading-and-writing-audio.rust.en-us.md

---

examples/reading-and-writing-audio/reading-and-writing-audio.assemblyscript.en-us.md

change **reccomended** to **recommended**

fix typo on reading-and-writing-audio.assemblyscript.en-us.md

---

examples/classes/classes.assemblyscript.en-us.md

Added an AssemblyScript/as-bind tutorial

AssemblyScript Class Tutorial

---

build-system/build.js
examples/exports/exports.assemblyscript.en-us.md
examples/exports/exports.rust.en-us.md
examples/hello-world/hello-world.assemblyscript.en-us.md
examples/hello-world/hello-world.rust.en-us.md
examples/importing-javascript-functions-into-webassembly/importing-javascript-functions-into-webassembly.assemblyscript.en-us.md
examples/importing-javascript-functions-into-webassembly/importing-javascript-functions-into-webassembly.rust.en-us.md
examples/introduction/introduction.all.en-us.md
examples/reading-and-writing-audio/reading-and-writing-audio.assemblyscript.en-us.md
examples/reading-and-writing-audio/reading-and-writing-audio.rust.en-us.md
examples/reading-and-writing-graphics/reading-and-writing-graphics.assemblyscript.en-us.md
examples/reading-and-writing-graphics/reading-and-writing-graphics.rust.en-us.md
examples/strings/strings.rust.en-us.md
examples/webassembly-linear-memory/webassembly-linear-memory.assemblyscript.en-us.md
examples/webassembly-linear-memory/webassembly-linear-memory.rust.en-us.md
package-lock.json
package.json
shell/additional-resources.html
shell/demo-redirect.html
shell/index.html
shell/js/demoRedirect.js
shell/js/index.js

closes #30 
closes #31 
closes #34 
Also, mentions Wasmtime and Lucet in more places :smile:

First Round of General Fixes

---

AUDIENCE.md
build-system/build.js
build-system/example-info.js
shell/index.html
shell/styles/examples-list.css

Fixed some more open issues

---

README.md
examples/strings/strings.rust.en-us.md

fix typos on the word community

---

examples/strings/demo/c/index.html

Super simple `npm run lint` :smile:

Fixed some linting

---

examples/introduction/introduction.all.pt-br.md
shell/js/index.js

relates to #94 
This allows for the language to be selected from the dropdown. Also contains some other small fixes :smile: 
cc @fbitti if the name is correct: "Brazilian Portuguese" in the dropdown :smile:

Enabled Brazilian Portuguese Language

---

examples/exports/demo/go/index.js
examples/exports/exports.go.en-us.md
examples/hello-world/hello-world.go.en-us.md
examples/importing-javascript-functions-into-webassembly/demo/go/index.js
examples/importing-javascript-functions-into-webassembly/demo/go/main.go
examples/importing-javascript-functions-into-webassembly/importing-javascript-functions-into-webassembly.go.en-us.md
examples/webassembly-linear-memory/demo/go/index.js
examples/webassembly-linear-memory/demo/go/main.go
examples/webassembly-linear-memory/webassembly-linear-memory.go.en-us.md

Added the remaining "Concepts" examples for Go / TinyGo

---

examples/reading-and-writing-audio/reading-and-writing-audio.assemblyscript.en-us.md

fix: typo in assemblyscript audio example

---

examples/reading-and-writing-audio/reading-and-writing-audio.assemblyscript.en-us.md
examples/reading-and-writing-audio/reading-and-writing-audio.rust.en-us.md
examples/reading-and-writing-audio/reading-and-writing-audio.rust.pt-br.md

closes #135
Fixes the broken link as mentioned in the issue, and replaces it with next steps for people reading WasmByExample 😄

Fixed the broken strings link

---

examples/hello-world/hello-world.rust.en-us.md

Changed `reccommended` to `recommended`

Fixed typo

---

build-system/build.js
package-lock.json
shell/about.html
shell/additional-resources.html
shell/all-examples-list.html
shell/example.html
shell/home.html
shell/partials/announcements.html
shell/styles/index.css

This PR adds some announcements per [my current full time career](https://twitter.com/torch2424/status/1526277524455493633), as well as my upcoming open source work. 😎

Added announcements bar to WasmByExample
